### ISSUE TITLE
Building mini-book

### ISSUE THREAD

**Issue by luukalt** [ExecutableBookProject/quantecon-mini-example#34]
Following the steps from demo book on https://jupyterbook.org/intro.html

When running the following command (in anaconda prompt on Windows 10 PC):

(wintest) C:\Users\luuka\quantecon-mini-example>jupyter-book build ./mini_book

It returns the following output and error:

Running Jupyter-Book v0.8.3
Traceback (most recent call last):
File “c:\users\luuka\anaconda3\envs\wintest\lib\runpy.py”, line 193, in _run_module_as_main
“main”, mod_spec)
File “c:\users\luuka\anaconda3\envs\wintest\lib\runpy.py”, line 85, in run_code
exec(code, run_globals)
File "C:\Users\luuka\Anaconda3\envs\wintest\Scripts\jupyter-book.exe_main.py", line 7, in
File “c:\users\luuka\anaconda3\envs\wintest\lib\site-packages\click\core.py”, line 829, in call
return self.main(*args, **kwargs)
File “c:\users\luuka\anaconda3\envs\wintest\lib\site-packages\click\core.py”, line 782, in main
rv = self.invoke(ctx)
File “c:\users\luuka\anaconda3\envs\wintest\lib\site-packages\click\core.py”, line 1259, in invoke
return process_result(sub_ctx.command.invoke(sub_ctx))
File “c:\users\luuka\anaconda3\envs\wintest\lib\site-packages\click\core.py”, line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File “c:\users\luuka\anaconda3\envs\wintest\lib\site-packages\click\core.py”, line 610, in invoke
return callback(*args, **kwargs)
File "c:\users\luuka\anaconda3\envs\wintest\lib\site-packages\jupyter_book\commands_init.py", line 199, in build
build_modified = max([os.stat(ii).st_mtime for ii in build_files])
ValueError: max() arg is an empty sequence

Does anybody have an idea what I could do to fix this?

Thanks in advance.

- Python Version: 3.7.9
- Package versions or output of `jupyter-book --version`:
Jupyter Book: 0.8.3
MyST-NB: 0.10.1
Sphinx Book Theme: 0.0.39
MyST-Parser: 0.12.10
Jupyter-Cache: 0.4.1
NbClient: 0.5.1
- Operating System: Windows 10

**Comment by ncolai** [comment]
I faced the same issue when running the demo. I fixed it by creating a dummy index.html in _build/html/, and then running jupyter-book build (name of book directory). Once I got that to work, I then removed the dummy file and reran jupyter-book build (book directory) to successfully load the book.

**Comment by litpuvn** [comment]
i cloned it and run as instruction and got this error in windows 10:
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\jupyter_book\sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "c:\python38\lib\site-packages\sphinx\application.py", line 348, in build
    self.builder.build_update()
  File "c:\python38\lib\site-packages\sphinx\builders\__init__.py", line 297, in build_update
    self.build(to_build,
  File "c:\python38\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "c:\python38\lib\site-packages\sphinx\builders\__init__.py", line 382, in read
    for docs in self.events.emit('env-get-outdated', self.env, added, changed, removed):
  File "c:\python38\lib\site-packages\sphinx\events.py", line 117, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function update_execution_cache at 0x0000016B516A4EE0> for event 'env-get-outdated' threw an exception (exception: Notebook does not appear to be JSON: '{\n "cells": [\n  {\n   "cell_type": "c...)

Python 3.8

Jupyter Book: 0.10.2
MyST-NB: 0.12.3
Sphinx Book Theme: 0.1.0
MyST-Parser: 0.13.7
Jupyter-Cache: 0.4.1
NbClient: 0.5.0
